FROM amazon/aws-sam-cli-build-image-python3.8

WORKDIR /opt/src
ADD . /opt/src

# Run pip to install all requirements
RUN pip install --no-cache-dir -r requirements_docker_dev.txt

ENTRYPOINT ./entrypoint.sh
